# golangci-test action
#
# Performs go-fmt and go-test and reports on errors.
#
name: golangci-gotest
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Format
      run: if [ "$(go fmt ./... | wc -l)" -gt 0 ]; then echo "go fmt failed"; exit 1; fi
      if: matrix.platform == 'ubuntu-latest'
    - name: Test
      run: go test -short ./...
