# golangci-goreleaser action
#
# Runs the goreleaser functions defined in .goreleaser.yml. The action
# will run when a new tag is pushed.
#
# Tokens are supplied for this file automatically by Github when the
# action is run.
#
# More information about how the go release is configured is in the
# .goreleaser.yml file. The file defines mechanisms such as how archive
# file names are configured and the contents of those files.
#
name: golangci-goreleaser
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
